schedule-value:      [30]
amount-training:     [25, 50, 100, 200]
n:                   [50]
ro:                  [1.]
loop-per-condition:  10
loop-per-simulation: 500
filename:            "sup_vi_other_vi.csv"
