schedule-value:      [60]
amount-training:     [500]
n:                   [25, 50, 75, 100]
ro:                  [0.001]
loop-per-condition:  10
loop-per-simulation: 500
filename:            "sup_td_noncontingent_n.csv"
