schedule-value:      [60]
amount-training:     [500]
n:                   [50]
ro:                  [0.001]
loop-per-condition:  10
loop-per-simulation: 500
filename:            "sup_sarsa_noncontingent.csv"
